
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'leftSUMSUBleftMULDIVleftNEGleftPOWDIV LPAREN MUL NEWLINE NUM POW RPAREN SUB SUMinput : \n| input lineline : NEWLINEline : exp NEWLINEline : error NEWLINEexp : NUMexp : exp SUM exp\n| exp SUB exp\n| exp MUL exp\n| exp DIV exp\n| exp POW expexp : SUB NUM %prec NEGexp : SUB LPAREN exp RPAREN %prec NEGexp : LPAREN exp RPAREN'
    
_lr_action_items = {'NEWLINE':([0,1,2,3,4,5,6,9,15,16,19,20,21,22,23,25,26,],[-1,3,-2,-3,9,15,-6,-4,-5,-12,-7,-8,-9,-10,-11,-14,-13,]),'error':([0,1,2,3,9,15,],[-1,5,-2,-3,-4,-5,]),'NUM':([0,1,2,3,7,8,9,10,11,12,13,14,15,17,],[-1,6,-2,-3,16,6,-4,6,6,6,6,6,-5,6,]),'SUB':([0,1,2,3,4,6,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,],[-1,7,-2,-3,11,-6,7,-4,7,7,7,7,7,-5,-12,7,11,-7,-8,-9,-10,-11,11,-14,-13,]),'LPAREN':([0,1,2,3,7,8,9,10,11,12,13,14,15,17,],[-1,8,-2,-3,17,8,-4,8,8,8,8,8,-5,8,]),'$end':([0,1,2,3,9,15,],[-1,0,-2,-3,-4,-5,]),'SUM':([4,6,16,18,19,20,21,22,23,24,25,26,],[10,-6,-12,10,-7,-8,-9,-10,-11,10,-14,-13,]),'MUL':([4,6,16,18,19,20,21,22,23,24,25,26,],[12,-6,-12,12,12,12,-9,-10,-11,12,-14,-13,]),'DIV':([4,6,16,18,19,20,21,22,23,24,25,26,],[13,-6,-12,13,13,13,-9,-10,-11,13,-14,-13,]),'POW':([4,6,16,18,19,20,21,22,23,24,25,26,],[14,-6,-12,14,14,14,14,14,-11,14,-14,-13,]),'RPAREN':([6,16,18,19,20,21,22,23,24,25,26,],[-6,-12,25,-7,-8,-9,-10,-11,26,-14,-13,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'input':([0,],[1,]),'line':([1,],[2,]),'exp':([1,8,10,11,12,13,14,17,],[4,18,19,20,21,22,23,24,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> input","S'",1,None,None,None),
  ('input -> <empty>','input',0,'p_input','ex2.py',140),
  ('input -> input line','input',2,'p_input','ex2.py',141),
  ('line -> NEWLINE','line',1,'p_line_newline','ex2.py',145),
  ('line -> exp NEWLINE','line',2,'p_line_exp','ex2.py',149),
  ('line -> error NEWLINE','line',2,'p_line_error','ex2.py',156),
  ('exp -> NUM','exp',1,'p_exp_num','ex2.py',161),
  ('exp -> exp SUM exp','exp',3,'p_exp_binary','ex2.py',170),
  ('exp -> exp SUB exp','exp',3,'p_exp_binary','ex2.py',171),
  ('exp -> exp MUL exp','exp',3,'p_exp_binary','ex2.py',172),
  ('exp -> exp DIV exp','exp',3,'p_exp_binary','ex2.py',173),
  ('exp -> exp POW exp','exp',3,'p_exp_binary','ex2.py',174),
  ('exp -> SUB NUM','exp',2,'p_exp_unary_minus_num','ex2.py',225),
  ('exp -> SUB LPAREN exp RPAREN','exp',4,'p_exp_unary_minus_group','ex2.py',236),
  ('exp -> LPAREN exp RPAREN','exp',3,'p_exp_group','ex2.py',246),
]
